version : '3.8'

services:
  java_app:
      container_name: java_app
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - postgres_db
  postgres_db:
    container_name: postgres_db
    image: postgres:16.1-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres